// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAd3yGPhGzpLRBeu-xhWAqg0ceNz-1yni0',
    appId: '1:571910961169:web:8c23f99fa7795e3629d9b0',
    messagingSenderId: '571910961169',
    projectId: 'portfolio-project-a8c86',
    authDomain: 'portfolio-project-a8c86.firebaseapp.com',
    storageBucket: 'portfolio-project-a8c86.firebasestorage.app',
    measurementId: 'G-K3EDLH51CC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEcUnD09x6DQ81Ojl-lcNyZYa2Dz6Ovj4',
    appId: '1:571910961169:android:1765ae2706f5084729d9b0',
    messagingSenderId: '571910961169',
    projectId: 'portfolio-project-a8c86',
    storageBucket: 'portfolio-project-a8c86.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhLBlidcf1EZvzC5_eKnp4D-l7TVUqWTE',
    appId: '1:571910961169:ios:7ff62ac6e9c0099e29d9b0',
    messagingSenderId: '571910961169',
    projectId: 'portfolio-project-a8c86',
    storageBucket: 'portfolio-project-a8c86.firebasestorage.app',
    androidClientId: '571910961169-9e5gqtt2nfai6av2th8gjbpkbl2h619b.apps.googleusercontent.com',
    iosClientId: '571910961169-jenr4sad5an56ubc7r6n475ckv3lpund.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhLBlidcf1EZvzC5_eKnp4D-l7TVUqWTE',
    appId: '1:571910961169:ios:7ff62ac6e9c0099e29d9b0',
    messagingSenderId: '571910961169',
    projectId: 'portfolio-project-a8c86',
    storageBucket: 'portfolio-project-a8c86.firebasestorage.app',
    androidClientId: '571910961169-9e5gqtt2nfai6av2th8gjbpkbl2h619b.apps.googleusercontent.com',
    iosClientId: '571910961169-jenr4sad5an56ubc7r6n475ckv3lpund.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAd3yGPhGzpLRBeu-xhWAqg0ceNz-1yni0',
    appId: '1:571910961169:web:80e97ff5ce33467429d9b0',
    messagingSenderId: '571910961169',
    projectId: 'portfolio-project-a8c86',
    authDomain: 'portfolio-project-a8c86.firebaseapp.com',
    storageBucket: 'portfolio-project-a8c86.firebasestorage.app',
    measurementId: 'G-YD13SQT02J',
  );

}