import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart'; // Generated by flutterfire CLI

void main() async {
  WidgetsFlutterBinding.ensureInitialized(); // Ensures Flutter binding is ready
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform, // Firebase config
  );
  runApp(const MainApp());
}

class MainApp extends StatelessWidget {
  const MainApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: Scaffold(
        body: Center(
          child: Text('Hello World! Firebase is initialized!'),
        ),
      ),
    );
  }
}
